# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "debian"
  config.vm.box_url = "https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_debian-7.1.0_provisionerless.box"
  config.vm.network :private_network, ip: "192.168.33.10"
  config.vm.synced_folder "../../", "/mnt/project", owner: "www-data", group: "vagrant", mount_options: [ "dmode=775", "fmode=774" ]

  config.omnibus.chef_version = :latest

  config.librarian_chef.cheffile_dir = "../chef"

  config.vm.provider :virtualbox do |vb|
    vb.name = "php-vagrant-vm"
    vb.memory = 384
    vb.gui = false
    vb.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
  end

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = ["../chef/cookbooks", "../chef/site-cookbooks"]
    chef.roles_path = "../chef/site-roles"
    chef.add_role "web"
    chef.json = {
      :mysql_password => "root",
      :mysql => {
        :server_debian_password => "root",
        :server_root_password => "root",
        :server_repl_password => "root",
        :bind_address => "127.0.0.1"
      },
      :apache => {
        :default_site_enabled => false
      },
      :project => {
        :site_name => "php-vagrant-vm",
        :server_name => "dev.php-vagrant-vm",
        :server_aliases => [],
        :docroot => "/mnt/project",
        :allow_override => "All"
      }
    }
  end
end
